---

- name: lxc > client > install > epel-release
  yum:
    name: epel-release
    state: present
    update_cache: true

- name: lxc > client > install > jq
  yum:
    name: jq
    state: present

- name: lxc > client > install > snapd
  yum:
    name: snapd
    state: present

- name: lxc > client > install > enable classic snap support
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: lxc > client > install > restart snapd.socket
  systemd:
    name: snapd.socket
    daemon_reload: true
    enabled: true
    state: restarted
  changed_when: false

- name: lxc > client > install > restart snapd.service
  systemd:
    name: snapd.service
    enabled: true
    state: restarted
  changed_when: false

- name: lxc > client > install > lxd
  shell: snap install lxd

- name: lxc > client > install > load lxd env
  shell: sh /etc/profile.d/snapd.sh
  changed_when: false

- name: lxc > client > install > debug > lxc version
  shell: lxc --version
  changed_when: false
